### PR TITLE
week1的作業(李昱醇)

### PR DESCRIPTION
**Pull request by mayonnaise0403**
李昱醇(毛毛)

http://18.178.198.252:3000/api/attraction/10
http://18.178.198.252:3000/api/attractions?page=0&keyword=藝文館所
http://18.178.198.252:3000/api/attractions?page=0&keyword=北
http://18.178.198.252:3000/api/categories

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your API always response 連線失敗 after some testings.

**Comment by mayonnaise0403** [comment]
> Your API always response 連線失敗 after some testings.
剛剛經過測試可以了~

**Comment by cwpeng** [comment]
Failed again. Web server should be 99.5% available in a year, so we should always to find out root cause of problem and fix it, not just restart.

Treat your code as a real product, and you will be an engineer.

If you fix issue, re-request review explicilty.

**Comment by mayonnaise0403** [comment]
> Failed again. Web server should be 99.5% available in a year, so we should always to find out root cause of problem and fix it, not just restart.
> 
> Treat your code as a real product, and you will be an engineer.
> 
> If you fix issue, re-request review explicilty.

抱歉老師 不小心按到re-request review

**Review by cwpeng — COMMENTED** [review]
OK. Wait your fix.

**Comment by mayonnaise0403** [comment]
> OK. Wait your fix.

希望這次可以了~> <
http://18.178.198.252:3000/api/attractions/?page=0&keyword=藝文館所
http://18.178.198.252:3000/api/attractions/?page=1&keyword=藝文館所

**Comment by mayonnaise0403** [comment]
> 

好像又失敗了 我再用用看 好像是nohup的問題

**Review by cwpeng — CHANGES_REQUESTED** [review]
No, failed again and again.

Test carefully, try every possible live URLs multiple times. Be patiant to handle every issue.

**Comment by mayonnaise0403** [comment]
> No, failed again and again.
> 
> Test carefully, try every possible live URLs multiple times. Be patiant to handle every issue.

老師我發現原因了!!!!!!!!!!!!!!!!!
就是~~~~~~~~~~~~
我有個function的連線池忘記關了!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
老師抱歉浪費您的時間!!真的太對不起了!!!!!!
自己試都沒有問題，原來是還沒超過連線池的數量，難怪自己試都成功。這次一定可以~~吧?

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But it's bad practice to do pagination depends on id because id is not always continuous number, id only means unique.

It's much better to use `LIMIT` in SQL to do pagination than do it in your own code. And you can get attractions joined with pictures at once.

Fix this issue and re-request review.

**Comment by mayonnaise0403** [comment]
> 

老師請問您指的是idName還是id~ 因為我的資料庫有設定主鍵為idName

**Review by cwpeng — COMMENTED** [review]
The same. If you set idName as primary key, it's bad practice to depend on it, because primary key is not promised to be continuous number, only unique.

**Comment by mayonnaise0403** [comment]
> > 
> 
> 老師請問您指的是idName還是id~ 因為我的資料庫有設定主鍵為idName



> The same. If you set idName as primary key, it's bad practice to depend on it, because primary key is not promised to be continuous number, only unique.

好惹~ 把需要迴圈跑mysql的部分都改掉了

**Comment by mayonnaise0403** [comment]
> > > 
> > 
> > 
> > 老師請問您指的是idName還是id~ 因為我的資料庫有設定主鍵為idName
> 
> > The same. If you set idName as primary key, it's bad practice to depend on it, because primary key is not promised to be continuous number, only unique.
> 
> 好惹~ 把需要迴圈跑mysql的部分都改掉了
阿 沒改到圖片的，改好跟你講qq

**Review by cwpeng — APPROVED** [review]
OK. Done.

Suggest get attraction list data at once by joining with pictures table, not one by one with for loop.

**Comment by mayonnaise0403** [comment]
> OK. Done.
> 
> Suggest get attraction list data at once by joining with pictures table, not one by one with for loop.

我把圖片的部分照您的方法修改了~ 抱歉剛剛晚上又有修改忘記上傳了，真的很抱歉~~
這個版本會比較好嗎?

**Comment by mayonnaise0403** [comment]
> > OK. Done.
> > Suggest get attraction list data at once by joining with pictures table, not one by one with for loop.
> 
> 我把圖片的部分照您的方法修改了~ 抱歉剛剛晚上又有修改忘記上傳了，真的很抱歉~~ 這個版本會比較好嗎?

只是可能沒有那麼易讀了，但是效率應該有變好吧~~

**Comment by cwpeng** [comment]
I just notice that I miss some critical issue in your code.

You still depends on idName to do range selection like this `idName >= %s and idName <= %s;`. idName is primary key, primary key is only promised unique, not continuous number. So, you cannot depend on it to do range selection. Just use `LIMIT` to do it.

Fix this issue. It's more critical than other parts.

**Comment by mayonnaise0403** [comment]
> I just notice that I miss some critical issue in your code.
> 
> You still depends on idName to do range selection like this `idName >= %s and idName <= %s;`. idName is primary key, primary key is only promised unique, not continuous number. So, you cannot depend on it to do range selection. Just use `LIMIT` to do it.
> 
> Fix this issue. It's more critical than other parts.

非常的感謝老師的提醒，差點就誤用了一輩子了，明天修正完傳給您~~ 謝謝老師!!辛苦惹!!

**Comment by mayonnaise0403** [comment]
> > I just notice that I miss some critical issue in your code.
> > You still depends on idName to do range selection like this `idName >= %s and idName <= %s;`. idName is primary key, primary key is only promised unique, not continuous number. So, you cannot depend on it to do range selection. Just use `LIMIT` to do it.
> > Fix this issue. It's more critical than other parts.
> 
> 非常的感謝老師的提醒，差點就誤用了一輩子了，明天修正完傳給您~~ 謝謝老師!!辛苦惹!!
這個寫法應該就有符合老師的需求了!!

**Comment by mayonnaise0403** [comment]
> > I just notice that I miss some critical issue in your code.
> > You still depends on idName to do range selection like this `idName >= %s and idName <= %s;`. idName is primary key, primary key is only promised unique, not continuous number. So, you cannot depend on it to do range selection. Just use `LIMIT` to do it.
> > Fix this issue. It's more critical than other parts.
> 
> 非常的感謝老師的提醒，差點就誤用了一輩子了，明天修正完傳給您~~ 謝謝老師!!辛苦惹!!

不知道這樣對不對QQ

**Comment by mayonnaise0403** [comment]
剛剛想到了完全不用依靠idName的方法了~ 這個應該就是老師所希望的方法了吧?

**Review by cwpeng — COMMENTED** [review]
Better. But you do not use `LIMIT` in keyword search.

**Comment by mayonnaise0403** [comment]
用好了~~
抱歉一直強迫老師看我的爛code QQ
老師辛苦惹!!

**Comment by cwpeng** [comment]
OK. You should merge this pull request before your next week job.

**Pull request merged**
