### PR TITLE
毛毛(李昱醇)

### PR DESCRIPTION
**Pull request by mayonnaise0403**
http://18.178.198.252:3000/attraction/1
http://18.178.198.252:3000/
老師抱歉 我好像不小心push到master了QQ

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
Good. Done. :)

Just be more careful in the future.

**Comment by cwpeng** [comment]
You can try to use Flask Blueprint to seperate API routes from app.py

**Comment by mayonnaise0403** [comment]
老師~ 這樣子分類可以嗎?

**Review by cwpeng — APPROVED** [review]
OK. It's up to you. ~

**Comment by mayonnaise0403** [comment]
http://18.178.198.252:3000/
http://18.178.198.252:3000/attraction/2
老師抱歉了~ 我上週忘記merge了QQ

**Review by cwpeng — CHANGES_REQUESTED** [review]
Sign out does not work properly. We should make sure API is completed before reloading page.

**Comment by mayonnaise0403** [comment]
抱歉沒有注意到這個細節> <
這樣應該可以吧?

**Review by cwpeng — APPROVED** [review]
Good. Done. :)

**Pull request merged**
